{'report_interval':500, 'epoch':10, 'batch_size':1, 'lr':1e-3,
     'cascade':6, 'chans':12, 'sens_chans':5,
     'net_name': f'test_6125_all_gaussian_augment',
     'acc_weight':{i:1 for i in range(2, 11)},
     'previous_model':'',
     'mask_mode':'equispaced',
     'use_SSIM_mask_train':True,
     'loss_type': 'SSIM',
     'add_gaussian_noise': True,
     'augment': True},
{'report_interval':500, 'epoch':10, 'batch_size':1, 'lr':1e-3,
     'net_name': 'test_6125_all_ssim_mask', 'cascade':6, 'chans':12, 'sens_chans':5,
     'acc_weight':{2:1, 3:1, 4:1, 5:1, 6:1, 7:1, 8:1, 9:1, 10:1},
     'previous_model':'', 'mask_mode':'equispaced','use_SSIM_mask_train':True},
{'report_interval':500, 'epoch':10, 'batch_size':1, 'lr':1e-3,
    'net_name': 'test_6125_all_ssim_mask_random', 'cascade':6, 'chans':12, 'sens_chans':5,
    'acc_weight':{2:1, 3:1, 4:1, 5:1, 6:1, 7:1, 8:1, 9:1, 10:1},
    'previous_model':'', 'mask_mode':'random','use_SSIM_mask_train':True},
{'report_interval':500, 'epoch':10, 'batch_size':1, 'lr':1e-3,
    'net_name': 'test_6125_all_ssim_mask_random_9', 'cascade':6, 'chans':12, 'sens_chans':5,
    'acc_weight':{2:1, 3:1, 4:1, 5:1, 6:1, 7:1, 8:1, 9:2, 10:1},
    'previous_model':'', 'mask_mode':'random','use_SSIM_mask_train':True},
{'report_interval':500, 'epoch':10, 'batch_size':1, 'lr':1e-3,
    'net_name': 'test_6125_all_ssim_mask_random_910', 'cascade':6, 'chans':12, 'sens_chans':5,
    'acc_weight':{2:1, 3:1, 4:1, 5:1, 6:1, 7:1, 8:1, 9:2, 10:2},
    'previous_model':'', 'mask_mode':'random','use_SSIM_mask_train':True}

acc = [{i:random.random() for i in range(2, 11)} for i in range(4)]

tasks = [
    {'report_interval':500, 'epoch':10, 'batch_size':1, 'lr':1e-3,
     'net_name': 'test_6125_all_random_2', 'cascade':6, 'chans':12, 'sens_chans':5,
     'acc_weight':acc[0],
     'previous_model':'', 'mask_mode':'equispaced','use_SSIM_mask_train':True},
    {'report_interval':500, 'epoch':10, 'batch_size':1, 'lr':1e-3,
     'net_name': 'test_6125_all_random_3', 'cascade':6, 'chans':12, 'sens_chans':5,
     'acc_weight':acc[1],
     'previous_model':'', 'mask_mode':'equispaced','use_SSIM_mask_train':True},
    {'report_interval':500, 'epoch':10, 'batch_size':1, 'lr':1e-3,
     'net_name': 'test_6125_all_random_4', 'cascade':6, 'chans':12, 'sens_chans':5,
     'acc_weight':acc[2],
     'previous_model':'', 'mask_mode':'equispaced','use_SSIM_mask_train':True},
    {'report_interval':500, 'epoch':10, 'batch_size':1, 'lr':1e-3,
     'net_name': 'test_6125_all_random_5', 'cascade':6, 'chans':12, 'sens_chans':5,
     'acc_weight':acc[3],
     'previous_model':'', 'mask_mode':'equispaced','use_SSIM_mask_train':True}
]

{'report_interval':500, 'epoch':10, 'batch_size':1, 'lr':1e-3,
    'cascade':6, 'chans':12, 'sens_chans':5,
    'net_name': f'test_6125_all_gaussian',
    'acc_weight':{i:1 for i in range(2, 11)},
    'previous_model':'',
    'mask_mode':'equispaced',
    'use_SSIM_mask_train':True,
    'loss_type': 'SSIM',
    'add_gaussian_noise': True,
    'augment': False},
{'report_interval':500, 'epoch':10, 'batch_size':1, 'lr':1e-3,
    'cascade':6, 'chans':12, 'sens_chans':5,
    'net_name': f'test_6125_all_L1',
    'acc_weight':{i:1 for i in range(2, 11)},
    'previous_model':'',
    'mask_mode':'equispaced',
    'use_SSIM_mask_train':True,
    'loss_type': 'L1',
    'add_gaussian_noise': False,
    'augment': False},
{'report_interval':500, 'epoch':10, 'batch_size':1, 'lr':1e-3,
    'cascade':6, 'chans':12, 'sens_chans':5,
    'net_name': f'test_6125_all_var1',
    'acc_weight':{2:1, 3:1, 4:1, 5:2, 6:1, 7:1, 8:2, 9:3, 10:2},
    'previous_model':'',
    'mask_mode':'equispaced',
    'use_SSIM_mask_train':True,
    'loss_type': 'SSIM',
    'add_gaussian_noise': False,
    'augment': False},
{'report_interval':500, 'epoch':10, 'batch_size':1, 'lr':1e-3,
    'cascade':6, 'chans':12, 'sens_chans':5,
    'net_name': f'test_6125_all_var2',
    'acc_weight':{2:1, 3:1, 4:1, 5:2, 6:2, 7:2, 8:2, 9:4, 10:3},
    'previous_model':'',
    'mask_mode':'equispaced',
    'use_SSIM_mask_train':True,
    'loss_type': 'L1',
    'add_gaussian_noise': False,
    'augment': False},
{'report_interval':500, 'epoch':50, 'batch_size':1, 'lr':1e-3,
     'cascade':6, 'chans':12, 'sens_chans':5,
     'net_name': f'test_6125_all_augment_50',
     'acc_weight':{i:1 for i in range(2, 11)},
     'previous_model':'',
     'mask_mode':'equispaced',
     'use_SSIM_mask_train':True,
     'loss_type': 'SSIM',
     'add_gaussian_noise': False,
     'augment': True},
{'report_interval':500, 'epoch':50, 'batch_size':1, 'lr':5e-4,
     'cascade':6, 'chans':12, 'sens_chans':5,
     'net_name': f'test_6125_all_ssim_mask_50_mask_var1',
     'acc_weight':{2:1, 3:1, 4:1, 5:2, 6:1, 7:1, 8:2, 9:3, 10:2},
     'previous_model':'test_6125_all_ssim_mask_40',
     'mask_mode':'equispaced',
     'use_SSIM_mask_train':True,
     'loss_type': 'SSIM',
     'add_gaussian_noise': False,
     'augment': False}, # mask 비율 다르게
{'report_interval':500, 'epoch':50, 'batch_size':1, 'lr':2.5e-4,
     'cascade':6, 'chans':12, 'sens_chans':5,
     'net_name': f'test_6125_all_ssim_mask_50_lr_half',
     'acc_weight':{2:1, 3:1, 4:1, 5:1, 6:1, 7:1, 8:1, 9:1, 10:1},
     'previous_model':'test_6125_all_ssim_mask_40',
     'mask_mode':'equispaced',
     'use_SSIM_mask_train':True,
     'loss_type': 'SSIM',
     'add_gaussian_noise': False,
     'augment': False}, # lr 절반
{'report_interval':500, 'epoch':50, 'batch_size':1, 'lr':1e-4,
    'cascade':6, 'chans':12, 'sens_chans':5,
    'net_name': f'test_6125_all_ssim_mask_50_lr_onetenth',
    'acc_weight':{2:1, 3:1, 4:1, 5:1, 6:1, 7:1, 8:1, 9:1, 10:1},
    'previous_model':'test_6125_all_ssim_mask_40',
    'mask_mode':'equispaced',
    'use_SSIM_mask_train':True,
    'loss_type': 'SSIM',
    'add_gaussian_noise': False,
    'augment': False}, # lr 1/10
{'report_interval':500, 'epoch':50, 'batch_size':1, 'lr':1e-4,
    'cascade':6, 'chans':12, 'sens_chans':5,
    'net_name': f'test_6125_all_ssim_mask_50_lr_onetenth_gaussian',
    'acc_weight':{2:1, 3:1, 4:1, 5:1, 6:1, 7:1, 8:1, 9:1, 10:1},
    'previous_model':'test_6125_all_ssim_mask_40',
    'mask_mode':'equispaced',
    'use_SSIM_mask_train':True,
    'loss_type': 'SSIM',
    'add_gaussian_noise': True,
    'augment': False}, # lr 1/10, gaussian
